---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-toml
          - id: check-xml
          # - id: check-yaml
          - id: end-of-file-fixer
            exclude: notebooks/tstoolbox_plot_bash.sh
          - id: fix-encoding-pragma
            args: [--remove]
          - id: mixed-line-ending
          - id: trailing-whitespace
            exclude: notebooks/tstoolbox_plot_bash.sh


    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: pretty-format-java
            args: [--autofix]
          - id: pretty-format-kotlin
            args: [--autofix]
          - id: pretty-format-toml
            args: [--autofix]

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.28.0
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt

    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
            language_version: python

    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            name: isort (python)
            # yamllint disable-line rule:line-length
            args: [--profile, black, --filter-files, --line-length, '88', --multi-line, '3']
          - id: isort
            name: isort (cython)
            types: [cython]
            # yamllint disable-line rule:line-length
            args: [--profile, black, --filter-files, --line-length, '88', --multi-line, '3']
          - id: isort
            name: isort (pyi)
            types: [pyi]
            # yamllint disable-line rule:line-length
            args: [--profile, black, --filter-files, --line-length, '88', --multi-line, '3']

    - repo: https://github.com/dfm/black_nbconvert
      rev: v0.4.0
      hooks:
          - id: black_nbconvert

    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.2.0
      hooks:
          - id: pyupgrade

    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.37.0
      hooks:
          - id: commitizen
            stages: [commit-msg]

    - repo: https://github.com/mwouts/jupytext
      rev: v1.14.1
      hooks:
          - id: jupytext
            args: [--from, ipynb, --to, auto:percent, --sync]
