#!/bin/bash

program=swmmtoolbox

pkgs="\
     setuptools \
     mando \
     numpy \
     scipy \
     matplotlib \
     nose \
     pandas \
     coverage \
     flake8 \
     "

envs=(~/python_ves/python-2.7.13 \
      ~/python_ves/python-3.5.2 \
      ~/python_ves/python-3.6.0)

for env in ${envs[@]}; do
    echo "${env}"

    source "${env}"/bin/activate
    pip install --upgrade pip
    pip install --upgrade --no-deps ${pkgs}
    pip uninstall -y ${program}
    rm -rf build
    python setup.py develop

    nosetests \
        --with-coverage \
        --cover-tests \
        --cover-package=${program} \
        --cover-branches \
        --cover-erase
    deactivate
done

source "${env}"/bin/activate
coverage erase
coverage run `which nosetests`
coverage report --include="${program}/*" --omit="tests/*"
coverage html --include="${program}/*" --omit="tests/*"
flake8 ${program}/__init__.py ${program}/${program}.py --exit-zero
deactivate

